from PyQt5.QtWidgets import QWidget
from PyQt5 import QtCore, QtWidgets, QtGui

class AppState:
    token = None

class Welcome_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(750, 522)
        Welcome.setStyleSheet("\n"
            "QWidget {\n"
            "    background-repeat: no-repeat;\n"
            "    background-position: center;\n"
            "\n"
            "}\n"
            "    QFrame {\n"
            "        background-color: rgba(255, 255, 255, 30%);\n"
            "        border-radius: 15px;\n"
            "    }\n"
            "    QLineEdit {\n"
            "        border: 1px solid #ccc;\n"
            "        padding: 8px 12px;\n"
            "        border-radius: 15px;\n"
            "        background-color: rgba(255, 255, 255, 80%);\n"
            "    }\n"
            "  \n"
            "    \n"
            "    QLabel {\n"
            "        color: black;\n"
            "    }")
        self.welcome_grid = QtWidgets.QGridLayout(Welcome)
        self.welcome_grid.setObjectName("welcome_grid")
        self.welcome_container = QtWidgets.QFrame(Welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_container.sizePolicy().hasHeightForWidth())
        self.welcome_container.setSizePolicy(sizePolicy)
        self.welcome_container.setMinimumSize(QtCore.QSize(400, 500))
        self.welcome_container.setMaximumSize(QtCore.QSize(400, 500))
        self.welcome_container.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.welcome_container.setObjectName("welcome_container")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.welcome_container)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.welcome_head = QtWidgets.QLabel(self.welcome_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_head.sizePolicy().hasHeightForWidth())
        self.welcome_head.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_head.setFont(font)
        self.welcome_head.setToolTip("")
        self.welcome_head.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_head.setObjectName("welcome_head")
        self.gridLayout_4.addWidget(self.welcome_head, 1, 0, 1, 1)
        self.welcome_btn_container = QtWidgets.QHBoxLayout()
        self.welcome_btn_container.setObjectName("welcome_btn_container")
        self.login_btn = QtWidgets.QPushButton(self.welcome_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.login_btn.setObjectName("login_btn")
        self.welcome_btn_container.addWidget(self.login_btn)
        self.register_btn = QtWidgets.QPushButton(self.welcome_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_btn.sizePolicy().hasHeightForWidth())
        self.register_btn.setSizePolicy(sizePolicy)
        self.register_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.register_btn.setObjectName("register_btn")
        self.welcome_btn_container.addWidget(self.register_btn)
        self.gridLayout_4.addLayout(self.welcome_btn_container, 3, 0, 1, 1)
        self.welcome_grid.addWidget(self.welcome_container, 0, 0, 1, 1)

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "Form"))
        self.welcome_head.setText(_translate("Welcome", "Epass"))
        self.login_btn.setText(_translate("Welcome", "Login"))
        self.register_btn.setText(_translate("Welcome", "Register"))

class Login_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Loginpage):
        Loginpage.setObjectName("Loginpage")
        Loginpage.resize(874, 621)
        Loginpage.setStyleSheet("\n"
            "    QWidget {\n"
            "        background-repeat: no-repeat;\n"
            "        background-position: center;\n"
            "    }\n"
            "    QFrame {\n"
            "        background-color: rgba(255, 255, 255, 30%);\n"
            "        border-radius: 15px;\n"
            "    }\n"
            "    QLineEdit {\n"
            "        border: 1px solid #ccc;\n"
            "        padding: 8px 12px;\n"
            "        border-radius: 15px;\n"
            "        background-color: rgba(255, 255, 255, 80%);\n"
            "    }\n"
            "    QPushButton {\n"
            "      \n"
            " \n"
            "    }\n"
            "    QLabel {\n"
            "        color:black;\n"
            "    }\n"
            "   \n"
            "   ")
        self.login_grid = QtWidgets.QGridLayout(Loginpage)
        self.login_grid.setContentsMargins(-1, -1, 11, -1)
        self.login_grid.setObjectName("login_grid")
        self.loginFrame = QtWidgets.QFrame(Loginpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginFrame.sizePolicy().hasHeightForWidth())
        self.loginFrame.setSizePolicy(sizePolicy)
        self.loginFrame.setMinimumSize(QtCore.QSize(400, 320))
        self.loginFrame.setMaximumSize(QtCore.QSize(400, 320))
        self.loginFrame.setToolTipDuration(-1)
        self.loginFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setLineWidth(1)
        self.loginFrame.setObjectName("loginFrame")
        self.frameLayout = QtWidgets.QVBoxLayout(self.loginFrame)
        self.frameLayout.setObjectName("frameLayout")
        self.login_header = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.login_header.setFont(font)
        self.login_header.setToolTip("")
        self.login_header.setAlignment(QtCore.Qt.AlignCenter)
        self.login_header.setObjectName("login_header")
        self.frameLayout.addWidget(self.login_header)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.frameLayout.addItem(spacerItem)
        self.username_inp = QtWidgets.QLineEdit(self.loginFrame)
        self.username_inp.setObjectName("username_inp")
        self.frameLayout.addWidget(self.username_inp)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_inp = QtWidgets.QLineEdit(self.loginFrame)
        self.password_inp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_inp.setObjectName("password_inp")
        self.horizontalLayout_2.addWidget(self.password_inp)
        self.echo_toggle_btn = QtWidgets.QPushButton(self.loginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.echo_toggle_btn.sizePolicy().hasHeightForWidth())
        self.echo_toggle_btn.setSizePolicy(sizePolicy)
        self.echo_toggle_btn.setMinimumSize(QtCore.QSize(30, 0))
        self.echo_toggle_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echo_toggle_btn.setObjectName("echo_toggle_btn")
        self.horizontalLayout_2.addWidget(self.echo_toggle_btn)
        self.frameLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frameLayout.addItem(spacerItem1)
        self.login_btn_container = QtWidgets.QHBoxLayout()
        self.login_btn_container.setObjectName("login_btn_container")
        self.back_btn = QtWidgets.QPushButton(self.loginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setMaximumSize(QtCore.QSize(150, 150))
        self.back_btn.setObjectName("back_btn")
        self.login_btn_container.addWidget(self.back_btn)
        self.login_btn = QtWidgets.QPushButton(self.loginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.login_btn.setObjectName("login_btn")
        self.login_btn_container.addWidget(self.login_btn)
        self.frameLayout.addLayout(self.login_btn_container)
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.frameLayout.addItem(spacerItem2)
        self.login_grid.addWidget(self.loginFrame, 0, 0, 1, 1)

        self.retranslateUi(Loginpage)
        QtCore.QMetaObject.connectSlotsByName(Loginpage)

    def retranslateUi(self, Loginpage):
        _translate = QtCore.QCoreApplication.translate
        self.login_header.setText(_translate("Loginpage", "Login"))
        self.username_inp.setPlaceholderText(_translate("Loginpage", "Username"))
        self.password_inp.setPlaceholderText(_translate("Loginpage", "Password"))
        self.echo_toggle_btn.setText(_translate("Loginpage", "👁️"))
        self.back_btn.setText(_translate("Loginpage", "Back"))
        self.login_btn.setText(_translate("Loginpage", "Login"))

class Register_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Registerpage):
        Registerpage.setObjectName("Registerpage")
        Registerpage.resize(868, 619)
        Registerpage.setStyleSheet("\n"
            "    QWidget {\n"
            "        background-repeat: no-repeat;\n"
            "        background-position: center;\n"
            "    }\n"
            "    QFrame {\n"
            "        background-color: rgba(255, 255, 255, 30%);\n"
            "        border-radius: 15px;\n"
            "    }\n"
            "    QLineEdit {\n"
            "        border: 1px solid #ccc;\n"
            "        padding: 8px 12px;\n"
            "        border-radius: 15px;\n"
            "        background-color: rgba(255, 255, 255, 80%);\n"
            "    }\n"
            "    QPushButton {\n"
            "      \n"
            " \n"
            "    }\n"
            "    QLabel {\n"
            "        color:black;\n"
            "    }\n"
            "   ")
        self.register_grid = QtWidgets.QGridLayout(Registerpage)
        self.register_grid.setObjectName("register_grid")
        self.registerFrame = QtWidgets.QFrame(Registerpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerFrame.sizePolicy().hasHeightForWidth())
        self.registerFrame.setSizePolicy(sizePolicy)
        self.registerFrame.setMinimumSize(QtCore.QSize(360, 350))
        self.registerFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.registerFrame.setObjectName("registerFrame")
        self.frameLayout = QtWidgets.QVBoxLayout(self.registerFrame)
        self.frameLayout.setContentsMargins(50, -1, 50, -1)
        self.frameLayout.setObjectName("frameLayout")
        self.register_header = QtWidgets.QLabel(self.registerFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.register_header.setFont(font)
        self.register_header.setAlignment(QtCore.Qt.AlignCenter)
        self.register_header.setObjectName("register_header")
        self.frameLayout.addWidget(self.register_header)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frameLayout.addItem(spacerItem)
        self.personal_num_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personal_num_inp.sizePolicy().hasHeightForWidth())
        self.personal_num_inp.setSizePolicy(sizePolicy)
        self.personal_num_inp.setMaximumSize(QtCore.QSize(250, 40))
        self.personal_num_inp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.personal_num_inp.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.personal_num_inp.setObjectName("personal_num_inp")
        self.frameLayout.addWidget(self.personal_num_inp)
        self.username_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_inp.sizePolicy().hasHeightForWidth())
        self.username_inp.setSizePolicy(sizePolicy)
        self.username_inp.setMaximumSize(QtCore.QSize(250, 16777215))
        self.username_inp.setObjectName("username_inp")
        self.frameLayout.addWidget(self.username_inp)
        self.password_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_inp.sizePolicy().hasHeightForWidth())
        self.password_inp.setSizePolicy(sizePolicy)
        self.password_inp.setMaximumSize(QtCore.QSize(250, 16777215))
        self.password_inp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_inp.setObjectName("password_inp")
        self.frameLayout.addWidget(self.password_inp)
        self.rpassword_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rpassword_inp.sizePolicy().hasHeightForWidth())
        self.rpassword_inp.setSizePolicy(sizePolicy)
        self.rpassword_inp.setMaximumSize(QtCore.QSize(250, 16777215))
        self.rpassword_inp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rpassword_inp.setObjectName("rpassword_inp")
        self.frameLayout.addWidget(self.rpassword_inp)
        self.register_btn_container = QtWidgets.QHBoxLayout()
        self.register_btn_container.setObjectName("register_btn_container")
        self.back_btn = QtWidgets.QPushButton(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setMaximumSize(QtCore.QSize(150, 150))
        self.back_btn.setObjectName("back_btn")
        self.register_btn_container.addWidget(self.back_btn)
        self.register_btn = QtWidgets.QPushButton(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_btn.sizePolicy().hasHeightForWidth())
        self.register_btn.setSizePolicy(sizePolicy)
        self.register_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.register_btn.setObjectName("register_btn")
        self.register_btn_container.addWidget(self.register_btn)
        self.frameLayout.addLayout(self.register_btn_container)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frameLayout.addItem(spacerItem1)
        self.register_grid.addWidget(self.registerFrame, 1, 0, 1, 1)

        self.retranslateUi(Registerpage)
        QtCore.QMetaObject.connectSlotsByName(Registerpage)

    def retranslateUi(self, Registerpage):
        _translate = QtCore.QCoreApplication.translate
        self.register_header.setText(_translate("Registerpage", "Register"))
        self.personal_num_inp.setPlaceholderText(_translate("Registerpage", "Personal number"))
        self.username_inp.setPlaceholderText(_translate("Registerpage", "Username"))
        self.password_inp.setPlaceholderText(_translate("Registerpage", "Password"))
        self.rpassword_inp.setPlaceholderText(_translate("Registerpage", "Repeat password"))
        self.back_btn.setText(_translate("Registerpage", "Back"))
        self.register_btn.setText(_translate("Registerpage", "Register"))

class Main_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    
    def setupUi(self, mainPage):
        mainPage.setObjectName("mainPage")
        mainPage.resize(863, 672)
        mainPage.setStyleSheet("\n"
"    QWidget#MainWidget {{\n"
"        background-repeat: no-repeat;\n"
"        background-position: center;\n"
"        background-origin: content;\n"
"        background-color: white;\n"
"    }}\n"
"   ")
        self.mainpage_grid = QtWidgets.QVBoxLayout(mainPage)
        self.mainpage_grid.setSpacing(3)
        self.mainpage_grid.setObjectName("mainpage_grid")
        self.tab = QtWidgets.QTabWidget(mainPage)
        self.tab.setStyleSheet("background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-origin: content;\n"
"background-color: white;")
        self.tab.setObjectName("tab")
        self.id_card_tab = QtWidgets.QWidget()
        self.id_card_tab.setObjectName("id_card_tab")
        self.tabLayout1 = QtWidgets.QVBoxLayout(self.id_card_tab)
        self.tabLayout1.setObjectName("tabLayout1")
        self.cred = QtWidgets.QHBoxLayout()
        self.cred.setObjectName("cred")
        self.photoLabel1 = QtWidgets.QLabel(self.id_card_tab)
        self.photoLabel1.setMinimumSize(QtCore.QSize(120, 90))
        self.photoLabel1.setMaximumSize(QtCore.QSize(140, 110))
        self.photoLabel1.setFrameShape(QtWidgets.QFrame.Box)
        self.photoLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.photoLabel1.setObjectName("photoLabel1")
        self.cred.addWidget(self.photoLabel1)
        self.cred_info = QtWidgets.QVBoxLayout()
        self.cred_info.setObjectName("cred_info")
        self.label_saxeli1 = QtWidgets.QLabel(self.id_card_tab)
        self.label_saxeli1.setObjectName("label_saxeli1")
        self.cred_info.addWidget(self.label_saxeli1)
        self.label_gvari1 = QtWidgets.QLabel(self.id_card_tab)
        self.label_gvari1.setObjectName("label_gvari1")
        self.cred_info.addWidget(self.label_gvari1)
        self.label_moqalakeoba1 = QtWidgets.QLabel(self.id_card_tab)
        self.label_moqalakeoba1.setObjectName("label_moqalakeoba1")
        self.cred_info.addWidget(self.label_moqalakeoba1)
        self.label_piradi_nomeri1 = QtWidgets.QLabel(self.id_card_tab)
        self.label_piradi_nomeri1.setObjectName("label_piradi_nomeri1")
        self.cred_info.addWidget(self.label_piradi_nomeri1)
        self.label_vada_inline = QtWidgets.QLabel(self.id_card_tab)
        self.label_vada_inline.setObjectName("label_vada_inline")
        self.cred_info.addWidget(self.label_vada_inline)
        self.cred.addLayout(self.cred_info)
        self.tabLayout1.addLayout(self.cred)
        self.id_nomeri = QtWidgets.QLabel(self.id_card_tab)
        self.id_nomeri.setObjectName("id_nomeri")
        self.tabLayout1.addWidget(self.id_nomeri)
        self.id_scroll = QtWidgets.QScrollArea(self.id_card_tab)
        self.id_scroll.setWidgetResizable(True)
        self.id_scroll.setObjectName("id_scroll")
        self.id_scroll_content = QtWidgets.QWidget()
        self.id_scroll_content.setGeometry(QtCore.QRect(0, 0, 811, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_scroll_content.sizePolicy().hasHeightForWidth())
        self.id_scroll_content.setSizePolicy(sizePolicy)
        self.id_scroll_content.setObjectName("id_scroll_content")
        self.scrollLayout1 = QtWidgets.QVBoxLayout(self.id_scroll_content)
        self.scrollLayout1.setObjectName("scrollLayout1")
        self.fine_inst = QtWidgets.QHBoxLayout()
        self.fine_inst.setContentsMargins(5, 5, 5, 5)
        self.fine_inst.setObjectName("fine_inst")
        self.label_id1 = QtWidgets.QLabel(self.id_scroll_content)
        self.label_id1.setObjectName("label_id1")
        self.fine_inst.addWidget(self.label_id1)
        self.label_amount1 = QtWidgets.QLabel(self.id_scroll_content)
        self.label_amount1.setObjectName("label_amount1")
        self.fine_inst.addWidget(self.label_amount1)
        self.label_message1 = QtWidgets.QLabel(self.id_scroll_content)
        self.label_message1.setObjectName("label_message1")
        self.fine_inst.addWidget(self.label_message1)
        self.btn_action1 = QtWidgets.QPushButton(self.id_scroll_content)
        self.btn_action1.setStyleSheet("")
        self.btn_action1.setObjectName("btn_action1")
        self.fine_inst.addWidget(self.btn_action1)
        self.scrollLayout1.addLayout(self.fine_inst)
        self.id_scroll.setWidget(self.id_scroll_content)
        self.tabLayout1.addWidget(self.id_scroll)
        self.tab.addTab(self.id_card_tab, "")
        self.passport_tab = QtWidgets.QWidget()
        self.passport_tab.setObjectName("passport_tab")
        self.tabLayout11 = QtWidgets.QVBoxLayout(self.passport_tab)
        self.tabLayout11.setObjectName("tabLayout11")
        self.cred_2 = QtWidgets.QHBoxLayout()
        self.cred_2.setObjectName("cred_2")
        self.photoLabel11 = QtWidgets.QLabel(self.passport_tab)
        self.photoLabel11.setMinimumSize(QtCore.QSize(120, 90))
        self.photoLabel11.setMaximumSize(QtCore.QSize(140, 110))
        self.photoLabel11.setFrameShape(QtWidgets.QFrame.Box)
        self.photoLabel11.setAlignment(QtCore.Qt.AlignCenter)
        self.photoLabel11.setObjectName("photoLabel11")
        self.cred_2.addWidget(self.photoLabel11)
        self.cred_info_2 = QtWidgets.QVBoxLayout()
        self.cred_info_2.setObjectName("cred_info_2")
        self.label_saxeli11 = QtWidgets.QLabel(self.passport_tab)
        self.label_saxeli11.setObjectName("label_saxeli11")
        self.cred_info_2.addWidget(self.label_saxeli11)
        self.label_gvari11 = QtWidgets.QLabel(self.passport_tab)
        self.label_gvari11.setObjectName("label_gvari11")
        self.cred_info_2.addWidget(self.label_gvari11)
        self.label_moqalakeoba11 = QtWidgets.QLabel(self.passport_tab)
        self.label_moqalakeoba11.setObjectName("label_moqalakeoba11")
        self.cred_info_2.addWidget(self.label_moqalakeoba11)
        self.label_piradi_nomeri11 = QtWidgets.QLabel(self.passport_tab)
        self.label_piradi_nomeri11.setObjectName("label_piradi_nomeri11")
        self.cred_info_2.addWidget(self.label_piradi_nomeri11)
        self.label_vada_inline1 = QtWidgets.QLabel(self.passport_tab)
        self.label_vada_inline1.setObjectName("label_vada_inline1")
        self.cred_info_2.addWidget(self.label_vada_inline1)
        self.cred_2.addLayout(self.cred_info_2)
        self.tabLayout11.addLayout(self.cred_2)
        self.passport_nomeri = QtWidgets.QLabel(self.passport_tab)
        self.passport_nomeri.setObjectName("passport_nomeri")
        self.tabLayout11.addWidget(self.passport_nomeri)
        self.passport_inner_tab = QtWidgets.QTabWidget(self.passport_tab)
        self.passport_inner_tab.setStyleSheet("")
        self.passport_inner_tab.setObjectName("passport_inner_tab")
        self.tab_visa = QtWidgets.QWidget()
        self.tab_visa.setStyleSheet("")
        self.tab_visa.setObjectName("tab_visa")
        self.visaLayout = QtWidgets.QVBoxLayout(self.tab_visa)
        self.visaLayout.setObjectName("visaLayout")
        self.visa_scroll = QtWidgets.QScrollArea(self.tab_visa)
        self.visa_scroll.setStyleSheet("")
        self.visa_scroll.setWidgetResizable(True)
        self.visa_scroll.setObjectName("visa_scroll")
        self.visa_scroll_contents = QtWidgets.QWidget()
        self.visa_scroll_contents.setGeometry(QtCore.QRect(0, 0, 139, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visa_scroll_contents.sizePolicy().hasHeightForWidth())
        self.visa_scroll_contents.setSizePolicy(sizePolicy)
        self.visa_scroll_contents.setStyleSheet("")
        self.visa_scroll_contents.setObjectName("visa_scroll_contents")
        self.gridlayout = QtWidgets.QGridLayout(self.visa_scroll_contents)
        self.gridlayout.setObjectName("gridlayout")
        self.visa_inst = QtWidgets.QHBoxLayout()
        self.visa_inst.setContentsMargins(5, 5, 5, 5)
        self.visa_inst.setObjectName("visa_inst")
        self.left_label_0 = QtWidgets.QLabel(self.visa_scroll_contents)
        self.left_label_0.setObjectName("left_label_0")
        self.visa_inst.addWidget(self.left_label_0)
        self.left_label_1 = QtWidgets.QLabel(self.visa_scroll_contents)
        self.left_label_1.setObjectName("left_label_1")
        self.visa_inst.addWidget(self.left_label_1)
        self.left_label_2 = QtWidgets.QLabel(self.visa_scroll_contents)
        self.left_label_2.setObjectName("left_label_2")
        self.visa_inst.addWidget(self.left_label_2)
        self.gridlayout.addLayout(self.visa_inst, 0, 0, 1, 1)
        self.visa_scroll.setWidget(self.visa_scroll_contents)
        self.visaLayout.addWidget(self.visa_scroll)
        self.passport_inner_tab.addTab(self.tab_visa, "")
        self.tab_borderstamp = QtWidgets.QWidget()
        self.tab_borderstamp.setObjectName("tab_borderstamp")
        self.borderstampLayout = QtWidgets.QVBoxLayout(self.tab_borderstamp)
        self.borderstampLayout.setObjectName("borderstampLayout")
        self.borderstamp_scroll = QtWidgets.QScrollArea(self.tab_borderstamp)
        self.borderstamp_scroll.setWidgetResizable(True)
        self.borderstamp_scroll.setObjectName("borderstamp_scroll")
        self.borderstamp_scroll_contents = QtWidgets.QWidget()
        self.borderstamp_scroll_contents.setGeometry(QtCore.QRect(0, 0, 783, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borderstamp_scroll_contents.sizePolicy().hasHeightForWidth())
        self.borderstamp_scroll_contents.setSizePolicy(sizePolicy)
        self.borderstamp_scroll_contents.setObjectName("borderstamp_scroll_contents")
        self.gridlayout1 = QtWidgets.QGridLayout(self.borderstamp_scroll_contents)
        self.gridlayout1.setObjectName("gridlayout1")
        self.borderstamp_inst = QtWidgets.QHBoxLayout()
        self.borderstamp_inst.setContentsMargins(5, 5, 5, 5)
        self.borderstamp_inst.setObjectName("borderstamp_inst")
        self.right_label_0 = QtWidgets.QLabel(self.borderstamp_scroll_contents)
        self.right_label_0.setObjectName("right_label_0")
        self.borderstamp_inst.addWidget(self.right_label_0)
        self.right_label_1 = QtWidgets.QLabel(self.borderstamp_scroll_contents)
        self.right_label_1.setObjectName("right_label_1")
        self.borderstamp_inst.addWidget(self.right_label_1)
        self.right_label_2 = QtWidgets.QLabel(self.borderstamp_scroll_contents)
        self.right_label_2.setObjectName("right_label_2")
        self.borderstamp_inst.addWidget(self.right_label_2)
        self.gridlayout1.addLayout(self.borderstamp_inst, 0, 0, 1, 1)
        self.borderstamp_scroll.setWidget(self.borderstamp_scroll_contents)
        self.borderstampLayout.addWidget(self.borderstamp_scroll)
        self.passport_inner_tab.addTab(self.tab_borderstamp, "")
        self.tabLayout11.addWidget(self.passport_inner_tab)
        self.tab.addTab(self.passport_tab, "")
        self.car_license_tab = QtWidgets.QWidget()
        self.car_license_tab.setObjectName("car_license_tab")
        self.tabLayout12 = QtWidgets.QVBoxLayout(self.car_license_tab)
        self.tabLayout12.setObjectName("tabLayout12")
        self.cred_3 = QtWidgets.QHBoxLayout()
        self.cred_3.setObjectName("cred_3")
        self.photoLabel12 = QtWidgets.QLabel(self.car_license_tab)
        self.photoLabel12.setMinimumSize(QtCore.QSize(120, 90))
        self.photoLabel12.setMaximumSize(QtCore.QSize(140, 110))
        self.photoLabel12.setFrameShape(QtWidgets.QFrame.Box)
        self.photoLabel12.setAlignment(QtCore.Qt.AlignCenter)
        self.photoLabel12.setObjectName("photoLabel12")
        self.cred_3.addWidget(self.photoLabel12)
        self.cred_info_3 = QtWidgets.QVBoxLayout()
        self.cred_info_3.setObjectName("cred_info_3")
        self.label_saxeli12 = QtWidgets.QLabel(self.car_license_tab)
        self.label_saxeli12.setObjectName("label_saxeli12")
        self.cred_info_3.addWidget(self.label_saxeli12)
        self.label_gvari12 = QtWidgets.QLabel(self.car_license_tab)
        self.label_gvari12.setObjectName("label_gvari12")
        self.cred_info_3.addWidget(self.label_gvari12)
        self.label_moqalakeoba12 = QtWidgets.QLabel(self.car_license_tab)
        self.label_moqalakeoba12.setObjectName("label_moqalakeoba12")
        self.cred_info_3.addWidget(self.label_moqalakeoba12)
        self.label_piradi_nomeri12 = QtWidgets.QLabel(self.car_license_tab)
        self.label_piradi_nomeri12.setObjectName("label_piradi_nomeri12")
        self.cred_info_3.addWidget(self.label_piradi_nomeri12)
        self.label_vada_inline2 = QtWidgets.QLabel(self.car_license_tab)
        self.label_vada_inline2.setObjectName("label_vada_inline2")
        self.cred_info_3.addWidget(self.label_vada_inline2)
        self.cred_3.addLayout(self.cred_info_3)
        self.tabLayout12.addLayout(self.cred_3)
        self.car_license_nomeri = QtWidgets.QLabel(self.car_license_tab)
        self.car_license_nomeri.setObjectName("car_license_nomeri")
        self.tabLayout12.addWidget(self.car_license_nomeri)
        self.car_license_scroll_2 = QtWidgets.QScrollArea(self.car_license_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_license_scroll_2.sizePolicy().hasHeightForWidth())
        self.car_license_scroll_2.setSizePolicy(sizePolicy)
        self.car_license_scroll_2.setMinimumSize(QtCore.QSize(0, 150))
        self.car_license_scroll_2.setWidgetResizable(True)
        self.car_license_scroll_2.setObjectName("car_license_scroll_2")
        self.car_license_scroll_content_2 = QtWidgets.QWidget()
        self.car_license_scroll_content_2.setGeometry(QtCore.QRect(0, 0, 811, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_license_scroll_content_2.sizePolicy().hasHeightForWidth())
        self.car_license_scroll_content_2.setSizePolicy(sizePolicy)
        self.car_license_scroll_content_2.setObjectName("car_license_scroll_content_2")
        self.scrollLayout1_2 = QtWidgets.QVBoxLayout(self.car_license_scroll_content_2)
        self.scrollLayout1_2.setObjectName("scrollLayout1_2")
        self.car_fine_inst_2 = QtWidgets.QHBoxLayout()
        self.car_fine_inst_2.setContentsMargins(5, 5, 5, 5)
        self.car_fine_inst_2.setObjectName("car_fine_inst_2")
        self.label_id1_2 = QtWidgets.QLabel(self.car_license_scroll_content_2)
        self.label_id1_2.setObjectName("label_id1_2")
        self.car_fine_inst_2.addWidget(self.label_id1_2)
        self.label_amount1_2 = QtWidgets.QLabel(self.car_license_scroll_content_2)
        self.label_amount1_2.setObjectName("label_amount1_2")
        self.car_fine_inst_2.addWidget(self.label_amount1_2)
        self.label_message1_2 = QtWidgets.QLabel(self.car_license_scroll_content_2)
        self.label_message1_2.setObjectName("label_message1_2")
        self.car_fine_inst_2.addWidget(self.label_message1_2)
        self.scrollLayout1_2.addLayout(self.car_fine_inst_2)
        self.car_license_scroll_2.setWidget(self.car_license_scroll_content_2)
        self.tabLayout12.addWidget(self.car_license_scroll_2)
        self.car_license_scroll = QtWidgets.QScrollArea(self.car_license_tab)
        self.car_license_scroll.setWidgetResizable(True)
        self.car_license_scroll.setObjectName("car_license_scroll")
        self.car_license_scroll_content = QtWidgets.QWidget()
        self.car_license_scroll_content.setGeometry(QtCore.QRect(0, 0, 811, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_license_scroll_content.sizePolicy().hasHeightForWidth())
        self.car_license_scroll_content.setSizePolicy(sizePolicy)
        self.car_license_scroll_content.setObjectName("car_license_scroll_content")
        self.scrollLayout11 = QtWidgets.QVBoxLayout(self.car_license_scroll_content)
        self.scrollLayout11.setObjectName("scrollLayout11")
        self.car_fine_inst = QtWidgets.QHBoxLayout()
        self.car_fine_inst.setContentsMargins(5, 5, 5, 5)
        self.car_fine_inst.setObjectName("car_fine_inst")
        self.label_id11 = QtWidgets.QLabel(self.car_license_scroll_content)
        self.label_id11.setObjectName("label_id11")
        self.car_fine_inst.addWidget(self.label_id11)
        self.label_amount11 = QtWidgets.QLabel(self.car_license_scroll_content)
        self.label_amount11.setObjectName("label_amount11")
        self.car_fine_inst.addWidget(self.label_amount11)
        self.label_message11 = QtWidgets.QLabel(self.car_license_scroll_content)
        self.label_message11.setObjectName("label_message11")
        self.car_fine_inst.addWidget(self.label_message11)
        self.btn_action11 = QtWidgets.QPushButton(self.car_license_scroll_content)
        self.btn_action11.setObjectName("btn_action11")
        self.car_fine_inst.addWidget(self.btn_action11)
        self.scrollLayout11.addLayout(self.car_fine_inst)
        self.car_license_scroll.setWidget(self.car_license_scroll_content)
        self.tabLayout12.addWidget(self.car_license_scroll)
        self.tab.addTab(self.car_license_tab, "")
        self.mainpage_grid.addWidget(self.tab)
        self.logout_btn = QtWidgets.QPushButton(mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_btn.sizePolicy().hasHeightForWidth())
        self.logout_btn.setSizePolicy(sizePolicy)
        self.logout_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logout_btn.setObjectName("logout_btn")
        self.mainpage_grid.addWidget(self.logout_btn)

        self.retranslateUi(mainPage)
        self.tab.setCurrentIndex(0)
        self.passport_inner_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainPage)

    def retranslateUi(self, mainPage):
        _translate = QtCore.QCoreApplication.translate
        mainPage.setWindowTitle(_translate("mainPage", "Main page"))
        self.photoLabel1.setText(_translate("mainPage", "Photo"))
        self.label_saxeli1.setText(_translate("mainPage", "სახელი"))
        self.label_gvari1.setText(_translate("mainPage", "გვარი"))
        self.label_moqalakeoba1.setText(_translate("mainPage", "მოქალაქე, სქესი, დაბადების თარიღი"))
        self.label_piradi_nomeri1.setText(_translate("mainPage", "პირადი ნომერი"))
        self.label_vada_inline.setText(_translate("mainPage", "ვადა"))
        self.id_nomeri.setText(_translate("mainPage", "Id number"))
        self.label_id1.setText(_translate("mainPage", "ID (jarimis tipi)"))
        self.label_amount1.setText(_translate("mainPage", "amount"))
        self.label_message1.setText(_translate("mainPage", "message"))
        self.btn_action1.setText(_translate("mainPage", "Gadavixade"))
        self.tab.setTabText(self.tab.indexOf(self.id_card_tab), _translate("mainPage", "Id card"))
        self.photoLabel11.setText(_translate("mainPage", "Photo"))
        self.label_saxeli11.setText(_translate("mainPage", "სახელი"))
        self.label_gvari11.setText(_translate("mainPage", "გვარი"))
        self.label_moqalakeoba11.setText(_translate("mainPage", "მოქალაქე, სქესი, დაბადების თარიღი"))
        self.label_piradi_nomeri11.setText(_translate("mainPage", "პირადი ნომერი"))
        self.label_vada_inline1.setText(_translate("mainPage", "ვადა"))
        self.passport_nomeri.setText(_translate("mainPage", "Passport number"))
        self.left_label_0.setText(_translate("mainPage", "aeroport"))
        self.left_label_1.setText(_translate("mainPage", "city"))
        self.left_label_2.setText(_translate("mainPage", "date"))
        self.passport_inner_tab.setTabText(self.passport_inner_tab.indexOf(self.tab_visa), _translate("mainPage", "visa"))
        self.right_label_0.setText(_translate("mainPage", "country"))
        self.right_label_1.setText(_translate("mainPage", "Gacemis vada date"))
        self.right_label_2.setText(_translate("mainPage", "Vadis gasvla date"))
        self.passport_inner_tab.setTabText(self.passport_inner_tab.indexOf(self.tab_borderstamp), _translate("mainPage", "borderstamp"))
        self.tab.setTabText(self.tab.indexOf(self.passport_tab), _translate("mainPage", "Passport"))
        self.photoLabel12.setText(_translate("mainPage", "Photo"))
        self.label_saxeli12.setText(_translate("mainPage", "სახელი"))
        self.label_gvari12.setText(_translate("mainPage", "გვარი"))
        self.label_moqalakeoba12.setText(_translate("mainPage", "მოქალაქე, სქესი, დაბადების თარიღი"))
        self.label_piradi_nomeri12.setText(_translate("mainPage", "პირადი ნომერი"))
        self.label_vada_inline2.setText(_translate("mainPage", "ვადა"))
        self.car_license_nomeri.setText(_translate("mainPage", "Car license number"))
        self.label_id1_2.setText(_translate("mainPage", "manqanis nomeri"))
        self.label_amount1_2.setText(_translate("mainPage", "brendi"))
        self.label_message1_2.setText(_translate("mainPage", "modeli"))
        self.label_id11.setText(_translate("mainPage", "Manqanis nomeri"))
        self.label_amount11.setText(_translate("mainPage", "amount"))
        self.label_message11.setText(_translate("mainPage", "Msg"))
        self.btn_action11.setText(_translate("mainPage", "Gadavixade"))
        self.tab.setTabText(self.tab.indexOf(self.car_license_tab), _translate("mainPage", "Car license"))
        self.logout_btn.setText(_translate("mainPage", "Log out"))
