from PyQt5.QtWidgets import QWidget
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import Qt

class AppState:
    token = None

class Welcome_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(750, 522)
        Welcome.setStyleSheet("\n"
            "QWidget {\n"
            "    background-repeat: no-repeat;\n"
            "    background-position: center;\n"
            "\n"
            "}\n"
            "    QFrame {\n"
            "        background-color: rgba(255, 255, 255, 30%);\n"
            "        border-radius: 15px;\n"
            "    }\n"
            "    QLineEdit {\n"
            "        border: 1px solid #ccc;\n"
            "        padding: 8px 12px;\n"
            "        border-radius: 15px;\n"
            "        background-color: rgba(255, 255, 255, 80%);\n"
            "    }\n"
            "  \n"
            "    \n"
            "    QLabel {\n"
            "        color: black;\n"
            "    }")
        self.welcome_grid = QtWidgets.QGridLayout(Welcome)
        self.welcome_grid.setObjectName("welcome_grid")
        self.welcome_container = QtWidgets.QFrame(Welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_container.sizePolicy().hasHeightForWidth())
        self.welcome_container.setSizePolicy(sizePolicy)
        self.welcome_container.setMinimumSize(QtCore.QSize(400, 500))
        self.welcome_container.setMaximumSize(QtCore.QSize(400, 500))
        self.welcome_container.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.welcome_container.setObjectName("welcome_container")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.welcome_container)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.welcome_head = QtWidgets.QLabel(self.welcome_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_head.sizePolicy().hasHeightForWidth())
        self.welcome_head.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_head.setFont(font)
        self.welcome_head.setToolTip("")
        self.welcome_head.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_head.setObjectName("welcome_head")
        self.gridLayout_4.addWidget(self.welcome_head, 1, 0, 1, 1)
        self.welcome_btn_container = QtWidgets.QHBoxLayout()
        self.welcome_btn_container.setObjectName("welcome_btn_container")
        self.login_btn = QtWidgets.QPushButton(self.welcome_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.login_btn.setObjectName("login_btn")
        self.welcome_btn_container.addWidget(self.login_btn)
        self.register_btn = QtWidgets.QPushButton(self.welcome_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_btn.sizePolicy().hasHeightForWidth())
        self.register_btn.setSizePolicy(sizePolicy)
        self.register_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.register_btn.setObjectName("register_btn")
        self.welcome_btn_container.addWidget(self.register_btn)
        self.gridLayout_4.addLayout(self.welcome_btn_container, 3, 0, 1, 1)
        self.welcome_grid.addWidget(self.welcome_container, 0, 0, 1, 1)

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        self.welcome_head.setText(_translate("Welcome", "Epass"))
        self.login_btn.setText(_translate("Welcome", "Login"))
        self.register_btn.setText(_translate("Welcome", "Register"))

class Login_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Loginpage):
        Loginpage.setObjectName("Loginpage")
        Loginpage.resize(874, 621)
        Loginpage.setStyleSheet("\n"
            "    QWidget {\n"
            "        background-repeat: no-repeat;\n"
            "        background-position: center;\n"
            "    }\n"
            "    QFrame {\n"
            "        background-color: rgba(255, 255, 255, 30%);\n"
            "        border-radius: 15px;\n"
            "    }\n"
            "    QLineEdit {\n"
            "        border: 1px solid #ccc;\n"
            "        padding: 8px 12px;\n"
            "        border-radius: 15px;\n"
            "        background-color: rgba(255, 255, 255, 80%);\n"
            "    }\n"
            "    QPushButton {\n"
            "      \n"
            " \n"
            "    }\n"
            "    QLabel {\n"
            "        color:black;\n"
            "    }\n"
            "   \n"
            "   ")
        self.login_grid = QtWidgets.QGridLayout(Loginpage)
        self.login_grid.setContentsMargins(-1, -1, 11, -1)
        self.login_grid.setObjectName("login_grid")
        self.loginFrame = QtWidgets.QFrame(Loginpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginFrame.sizePolicy().hasHeightForWidth())
        self.loginFrame.setSizePolicy(sizePolicy)
        self.loginFrame.setMinimumSize(QtCore.QSize(400, 320))
        self.loginFrame.setMaximumSize(QtCore.QSize(400, 320))
        self.loginFrame.setToolTipDuration(-1)
        self.loginFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setLineWidth(1)
        self.loginFrame.setObjectName("loginFrame")
        self.frameLayout = QtWidgets.QVBoxLayout(self.loginFrame)
        self.frameLayout.setObjectName("frameLayout")
        self.login_header = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.login_header.setFont(font)
        self.login_header.setToolTip("")
        self.login_header.setAlignment(QtCore.Qt.AlignCenter)
        self.login_header.setObjectName("login_header")
        self.frameLayout.addWidget(self.login_header)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.frameLayout.addItem(spacerItem)
        self.username_inp = QtWidgets.QLineEdit(self.loginFrame)
        self.username_inp.setObjectName("username_inp")
        self.frameLayout.addWidget(self.username_inp)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_inp = QtWidgets.QLineEdit(self.loginFrame)
        self.password_inp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_inp.setObjectName("password_inp")
        self.horizontalLayout_2.addWidget(self.password_inp)
        self.echo_toggle_btn = QtWidgets.QPushButton(self.loginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.echo_toggle_btn.sizePolicy().hasHeightForWidth())
        self.echo_toggle_btn.setSizePolicy(sizePolicy)
        self.echo_toggle_btn.setMinimumSize(QtCore.QSize(30, 0))
        self.echo_toggle_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echo_toggle_btn.setObjectName("echo_toggle_btn")
        self.horizontalLayout_2.addWidget(self.echo_toggle_btn)
        self.frameLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frameLayout.addItem(spacerItem1)
        self.login_btn_container = QtWidgets.QHBoxLayout()
        self.login_btn_container.setObjectName("login_btn_container")
        self.back_btn = QtWidgets.QPushButton(self.loginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setMaximumSize(QtCore.QSize(150, 150))
        self.back_btn.setObjectName("back_btn")
        self.login_btn_container.addWidget(self.back_btn)
        self.login_btn = QtWidgets.QPushButton(self.loginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.login_btn.setObjectName("login_btn")
        self.login_btn_container.addWidget(self.login_btn)
        self.frameLayout.addLayout(self.login_btn_container)
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.frameLayout.addItem(spacerItem2)
        self.login_grid.addWidget(self.loginFrame, 0, 0, 1, 1)

        self.retranslateUi(Loginpage)
        QtCore.QMetaObject.connectSlotsByName(Loginpage)

    def retranslateUi(self, Loginpage):
        _translate = QtCore.QCoreApplication.translate
        self.login_header.setText(_translate("Loginpage", "Login"))
        self.username_inp.setPlaceholderText(_translate("Loginpage", "Username"))
        self.password_inp.setPlaceholderText(_translate("Loginpage", "Password"))
        self.echo_toggle_btn.setText(_translate("Loginpage", "👁️"))
        self.back_btn.setText(_translate("Loginpage", "Back"))
        self.login_btn.setText(_translate("Loginpage", "Login"))

class Register_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Registerpage):
        Registerpage.setObjectName("Registerpage")
        Registerpage.resize(868, 619)
        Registerpage.setStyleSheet("\n"
            "    QWidget {\n"
            "        background-repeat: no-repeat;\n"
            "        background-position: center;\n"
            "    }\n"
            "    QFrame {\n"
            "        background-color: rgba(255, 255, 255, 30%);\n"
            "        border-radius: 15px;\n"
            "    }\n"
            "    QLineEdit {\n"
            "        border: 1px solid #ccc;\n"
            "        padding: 8px 12px;\n"
            "        border-radius: 15px;\n"
            "        background-color: rgba(255, 255, 255, 80%);\n"
            "    }\n"
            "    QPushButton {\n"
            "      \n"
            " \n"
            "    }\n"
            "    QLabel {\n"
            "        color:black;\n"
            "    }\n"
            "   ")
        self.register_grid = QtWidgets.QGridLayout(Registerpage)
        self.register_grid.setObjectName("register_grid")
        self.registerFrame = QtWidgets.QFrame(Registerpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerFrame.sizePolicy().hasHeightForWidth())
        self.registerFrame.setSizePolicy(sizePolicy)
        self.registerFrame.setMinimumSize(QtCore.QSize(360, 350))
        self.registerFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.registerFrame.setObjectName("registerFrame")
        self.frameLayout = QtWidgets.QVBoxLayout(self.registerFrame)
        self.frameLayout.setContentsMargins(50, -1, 50, -1)
        self.frameLayout.setObjectName("frameLayout")
        self.register_header = QtWidgets.QLabel(self.registerFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.register_header.setFont(font)
        self.register_header.setAlignment(QtCore.Qt.AlignCenter)
        self.register_header.setObjectName("register_header")
        self.frameLayout.addWidget(self.register_header)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frameLayout.addItem(spacerItem)
        self.personal_num_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personal_num_inp.sizePolicy().hasHeightForWidth())
        self.personal_num_inp.setSizePolicy(sizePolicy)
        self.personal_num_inp.setMaximumSize(QtCore.QSize(250, 40))
        self.personal_num_inp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.personal_num_inp.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.personal_num_inp.setObjectName("personal_num_inp")
        self.frameLayout.addWidget(self.personal_num_inp)
        self.username_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_inp.sizePolicy().hasHeightForWidth())
        self.username_inp.setSizePolicy(sizePolicy)
        self.username_inp.setMaximumSize(QtCore.QSize(250, 16777215))
        self.username_inp.setObjectName("username_inp")
        self.frameLayout.addWidget(self.username_inp)
        self.password_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_inp.sizePolicy().hasHeightForWidth())
        self.password_inp.setSizePolicy(sizePolicy)
        self.password_inp.setMaximumSize(QtCore.QSize(250, 16777215))
        self.password_inp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_inp.setObjectName("password_inp")
        self.frameLayout.addWidget(self.password_inp)
        self.rpassword_inp = QtWidgets.QLineEdit(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rpassword_inp.sizePolicy().hasHeightForWidth())
        self.rpassword_inp.setSizePolicy(sizePolicy)
        self.rpassword_inp.setMaximumSize(QtCore.QSize(250, 16777215))
        self.rpassword_inp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rpassword_inp.setObjectName("rpassword_inp")
        self.frameLayout.addWidget(self.rpassword_inp)
        self.register_btn_container = QtWidgets.QHBoxLayout()
        self.register_btn_container.setObjectName("register_btn_container")
        self.back_btn = QtWidgets.QPushButton(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setMaximumSize(QtCore.QSize(150, 150))
        self.back_btn.setObjectName("back_btn")
        self.register_btn_container.addWidget(self.back_btn)
        self.register_btn = QtWidgets.QPushButton(self.registerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_btn.sizePolicy().hasHeightForWidth())
        self.register_btn.setSizePolicy(sizePolicy)
        self.register_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.register_btn.setObjectName("register_btn")
        self.register_btn_container.addWidget(self.register_btn)
        self.frameLayout.addLayout(self.register_btn_container)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frameLayout.addItem(spacerItem1)
        self.register_grid.addWidget(self.registerFrame, 1, 0, 1, 1)

        self.retranslateUi(Registerpage)
        QtCore.QMetaObject.connectSlotsByName(Registerpage)

    def retranslateUi(self, Registerpage):
        _translate = QtCore.QCoreApplication.translate
        self.register_header.setText(_translate("Registerpage", "Register"))
        self.personal_num_inp.setPlaceholderText(_translate("Registerpage", "Personal number"))
        self.username_inp.setPlaceholderText(_translate("Registerpage", "Username"))
        self.password_inp.setPlaceholderText(_translate("Registerpage", "Password"))
        self.rpassword_inp.setPlaceholderText(_translate("Registerpage", "Repeat password"))
        self.back_btn.setText(_translate("Registerpage", "Back"))
        self.register_btn.setText(_translate("Registerpage", "Register"))

class Main_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    
    def setupUi(self, mainPage):
        mainPage.setObjectName("mainPage")
        mainPage.resize(863, 672)
        mainPage.setStyleSheet("\n"
"    QWidget#MainWidget {{\n"
"        background-repeat: no-repeat;\n"
"        background-position: center;\n"
"        background-origin: content;\n"
"        background-color: white;\n"
"    }}\n"
"   ")
        self.mainpage_grid = QtWidgets.QVBoxLayout(mainPage)
        self.mainpage_grid.setSpacing(3)
        self.mainpage_grid.setObjectName("mainpage_grid")
        self.tab = QtWidgets.QTabWidget(mainPage)
        self.tab.setStyleSheet("background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-origin: content;\n"
"background-color: white;")
        self.tab.setObjectName("tab")
        self.id_card_tab = QtWidgets.QWidget()
        self.id_card_tab.setObjectName("id_card_tab")
        self.tabLayout1 = QtWidgets.QVBoxLayout(self.id_card_tab)
        self.tabLayout1.setObjectName("tabLayout1")
        self.cred = QtWidgets.QHBoxLayout()
        self.cred.setObjectName("cred")
        self.id_photo = QtWidgets.QLabel(self.id_card_tab)
        self.id_photo.setMinimumSize(QtCore.QSize(120, 90))
        self.id_photo.setMaximumSize(QtCore.QSize(140, 110))
        self.id_photo.setFrameShape(QtWidgets.QFrame.Box)
        self.id_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.id_photo.setObjectName("id_photo")
        self.cred.addWidget(self.id_photo)
        self.cred_info = QtWidgets.QVBoxLayout()
        self.cred_info.setObjectName("cred_info")
        self.id_name = QtWidgets.QLabel(self.id_card_tab)
        self.id_name.setObjectName("id_name")
        self.cred_info.addWidget(self.id_name)
        self.id_lname = QtWidgets.QLabel(self.id_card_tab)
        self.id_lname.setObjectName("id_lname")
        self.cred_info.addWidget(self.id_lname)
        self.id_cit_sex_bdate = QtWidgets.QLabel(self.id_card_tab)
        self.id_cit_sex_bdate.setObjectName("id_cit_sex_bdate")
        self.cred_info.addWidget(self.id_cit_sex_bdate)
        self.id_personal_num = QtWidgets.QLabel(self.id_card_tab)
        self.id_personal_num.setObjectName("id_personal_num")
        self.cred_info.addWidget(self.id_personal_num)
        self.id_date = QtWidgets.QLabel(self.id_card_tab)
        self.id_date.setObjectName("id_date")
        self.cred_info.addWidget(self.id_date)
        self.cred.addLayout(self.cred_info)
        self.tabLayout1.addLayout(self.cred)
        self.id_nomeri = QtWidgets.QLabel(self.id_card_tab)
        self.id_nomeri.setObjectName("id_nomeri")
        self.tabLayout1.addWidget(self.id_nomeri)
        self.id_scroll = QtWidgets.QScrollArea(self.id_card_tab)
        self.id_scroll.setWidgetResizable(True)
        self.id_scroll.setObjectName("id_scroll")
        self.id_scroll_content = QtWidgets.QWidget()
        self.id_scroll_content.setGeometry(QtCore.QRect(0, 0, 811, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_scroll_content.sizePolicy().hasHeightForWidth())
        self.id_scroll_content.setSizePolicy(sizePolicy)
        self.id_scroll_content.setObjectName("id_scroll_content")
        self.id_content = QtWidgets.QVBoxLayout(self.id_scroll_content)
        self.id_content.setObjectName("id_content")
        self.id_scroll.setWidget(self.id_scroll_content)
        self.tabLayout1.addWidget(self.id_scroll)
        self.tab.addTab(self.id_card_tab, "")
        self.passport_tab = QtWidgets.QWidget()
        self.passport_tab.setObjectName("passport_tab")
        self.tabLayout11 = QtWidgets.QVBoxLayout(self.passport_tab)
        self.tabLayout11.setObjectName("tabLayout11")
        self.cred_2 = QtWidgets.QHBoxLayout()
        self.cred_2.setObjectName("cred_2")
        self.pass_photo = QtWidgets.QLabel(self.passport_tab)
        self.pass_photo.setMinimumSize(QtCore.QSize(120, 90))
        self.pass_photo.setMaximumSize(QtCore.QSize(140, 110))
        self.pass_photo.setFrameShape(QtWidgets.QFrame.Box)
        self.pass_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_photo.setObjectName("pass_photo")
        self.cred_2.addWidget(self.pass_photo)
        self.cred_info_2 = QtWidgets.QVBoxLayout()
        self.cred_info_2.setObjectName("cred_info_2")
        self.pass_name = QtWidgets.QLabel(self.passport_tab)
        self.pass_name.setObjectName("pass_name")
        self.cred_info_2.addWidget(self.pass_name)
        self.pass_lname = QtWidgets.QLabel(self.passport_tab)
        self.pass_lname.setObjectName("pass_lname")
        self.cred_info_2.addWidget(self.pass_lname)
        self.pass_cit_sex_bdate = QtWidgets.QLabel(self.passport_tab)
        self.pass_cit_sex_bdate.setObjectName("pass_cit_sex_bdate")
        self.cred_info_2.addWidget(self.pass_cit_sex_bdate)
        self.pass_personal_num = QtWidgets.QLabel(self.passport_tab)
        self.pass_personal_num.setObjectName("pass_personal_num")
        self.cred_info_2.addWidget(self.pass_personal_num)
        self.pass_date = QtWidgets.QLabel(self.passport_tab)
        self.pass_date.setObjectName("pass_date")
        self.cred_info_2.addWidget(self.pass_date)
        self.cred_2.addLayout(self.cred_info_2)
        self.tabLayout11.addLayout(self.cred_2)
        self.passport_nomeri = QtWidgets.QLabel(self.passport_tab)
        self.passport_nomeri.setObjectName("passport_nomeri")
        self.tabLayout11.addWidget(self.passport_nomeri)
        self.passport_inner_tab = QtWidgets.QTabWidget(self.passport_tab)
        self.passport_inner_tab.setStyleSheet("")
        self.passport_inner_tab.setObjectName("passport_inner_tab")
        self.tab_visa = QtWidgets.QWidget()
        self.tab_visa.setStyleSheet("")
        self.tab_visa.setObjectName("tab_visa")
        self.visaLayout = QtWidgets.QVBoxLayout(self.tab_visa)
        self.visaLayout.setObjectName("visaLayout")
        self.visa_scroll = QtWidgets.QScrollArea(self.tab_visa)
        self.visa_scroll.setStyleSheet("")
        self.visa_scroll.setWidgetResizable(True)
        self.visa_scroll.setObjectName("visa_scroll")
        self.visa_scroll_contents = QtWidgets.QWidget()
        self.visa_scroll_contents.setGeometry(QtCore.QRect(0, 0, 783, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visa_scroll_contents.sizePolicy().hasHeightForWidth())
        self.visa_scroll_contents.setSizePolicy(sizePolicy)
        self.visa_scroll_contents.setStyleSheet("")
        self.visa_scroll_contents.setObjectName("visa_scroll_contents")
        self.visa_content = QtWidgets.QVBoxLayout(self.visa_scroll_contents)
        self.visa_content.setObjectName("visa_content")
        self.visa_scroll.setWidget(self.visa_scroll_contents)
        self.visaLayout.addWidget(self.visa_scroll)
        self.passport_inner_tab.addTab(self.tab_visa, "")
        self.tab_borderstamp = QtWidgets.QWidget()
        self.tab_borderstamp.setObjectName("tab_borderstamp")
        self.borderstampLayout = QtWidgets.QVBoxLayout(self.tab_borderstamp)
        self.borderstampLayout.setObjectName("borderstampLayout")
        self.borderstamp_scroll = QtWidgets.QScrollArea(self.tab_borderstamp)
        self.borderstamp_scroll.setWidgetResizable(True)
        self.borderstamp_scroll.setObjectName("borderstamp_scroll")
        self.borderstamp_scroll_contents = QtWidgets.QWidget()
        self.borderstamp_scroll_contents.setGeometry(QtCore.QRect(0, 0, 783, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borderstamp_scroll_contents.sizePolicy().hasHeightForWidth())
        self.borderstamp_scroll_contents.setSizePolicy(sizePolicy)
        self.borderstamp_scroll_contents.setObjectName("borderstamp_scroll_contents")
        self.borderstamp_content = QtWidgets.QVBoxLayout(self.borderstamp_scroll_contents)
        self.borderstamp_content.setObjectName("borderstamp_content")
        self.borderstamp_scroll.setWidget(self.borderstamp_scroll_contents)
        self.borderstampLayout.addWidget(self.borderstamp_scroll)
        self.passport_inner_tab.addTab(self.tab_borderstamp, "")
        self.tabLayout11.addWidget(self.passport_inner_tab)
        self.tab.addTab(self.passport_tab, "")
        self.car_license_tab = QtWidgets.QWidget()
        self.car_license_tab.setObjectName("car_license_tab")
        self.tabLayout12 = QtWidgets.QVBoxLayout(self.car_license_tab)
        self.tabLayout12.setObjectName("tabLayout12")
        self.cred_3 = QtWidgets.QHBoxLayout()
        self.cred_3.setObjectName("cred_3")
        self.car_photo = QtWidgets.QLabel(self.car_license_tab)
        self.car_photo.setMinimumSize(QtCore.QSize(120, 90))
        self.car_photo.setMaximumSize(QtCore.QSize(140, 110))
        self.car_photo.setFrameShape(QtWidgets.QFrame.Box)
        self.car_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.car_photo.setObjectName("car_photo")
        self.cred_3.addWidget(self.car_photo)
        self.cred_info_3 = QtWidgets.QVBoxLayout()
        self.cred_info_3.setObjectName("cred_info_3")
        self.car_name = QtWidgets.QLabel(self.car_license_tab)
        self.car_name.setObjectName("car_name")
        self.cred_info_3.addWidget(self.car_name)
        self.car_lname = QtWidgets.QLabel(self.car_license_tab)
        self.car_lname.setObjectName("car_lname")
        self.cred_info_3.addWidget(self.car_lname)
        self.car_cit_sex_bdate = QtWidgets.QLabel(self.car_license_tab)
        self.car_cit_sex_bdate.setObjectName("car_cit_sex_bdate")
        self.cred_info_3.addWidget(self.car_cit_sex_bdate)
        self.car_personal_num = QtWidgets.QLabel(self.car_license_tab)
        self.car_personal_num.setObjectName("car_personal_num")
        self.cred_info_3.addWidget(self.car_personal_num)
        self.car_date = QtWidgets.QLabel(self.car_license_tab)
        self.car_date.setObjectName("car_date")
        self.cred_info_3.addWidget(self.car_date)
        self.cred_3.addLayout(self.cred_info_3)
        self.tabLayout12.addLayout(self.cred_3)
        self.car_license_nomeri = QtWidgets.QLabel(self.car_license_tab)
        self.car_license_nomeri.setObjectName("car_license_nomeri")
        self.tabLayout12.addWidget(self.car_license_nomeri)
        self.add_btn_horizontal = QtWidgets.QHBoxLayout()
        self.add_btn_horizontal.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.add_btn_horizontal.setObjectName("add_btn_horizontal")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.add_btn_horizontal.addItem(spacerItem)
        self.add_car_btn = QtWidgets.QPushButton(self.car_license_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_car_btn.sizePolicy().hasHeightForWidth())
        self.add_car_btn.setSizePolicy(sizePolicy)
        self.add_car_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.add_car_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.add_car_btn.setObjectName("add_car_btn")
        self.add_btn_horizontal.addWidget(self.add_car_btn)
        self.tabLayout12.addLayout(self.add_btn_horizontal)
        self.car_license_scroll_2 = QtWidgets.QScrollArea(self.car_license_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_license_scroll_2.sizePolicy().hasHeightForWidth())
        self.car_license_scroll_2.setSizePolicy(sizePolicy)
        self.car_license_scroll_2.setMinimumSize(QtCore.QSize(0, 150))
        self.car_license_scroll_2.setWidgetResizable(True)
        self.car_license_scroll_2.setObjectName("car_license_scroll_2")
        self.car_license_scroll_content_2 = QtWidgets.QWidget()
        self.car_license_scroll_content_2.setGeometry(QtCore.QRect(0, 0, 811, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_license_scroll_content_2.sizePolicy().hasHeightForWidth())
        self.car_license_scroll_content_2.setSizePolicy(sizePolicy)
        self.car_license_scroll_content_2.setObjectName("car_license_scroll_content_2")
        self.car_content = QtWidgets.QVBoxLayout(self.car_license_scroll_content_2)
        self.car_content.setObjectName("car_content")
        self.car_license_scroll_2.setWidget(self.car_license_scroll_content_2)
        self.tabLayout12.addWidget(self.car_license_scroll_2)
        self.car_license_scroll = QtWidgets.QScrollArea(self.car_license_tab)
        self.car_license_scroll.setWidgetResizable(True)
        self.car_license_scroll.setObjectName("car_license_scroll")
        self.car_license_scroll_content = QtWidgets.QWidget()
        self.car_license_scroll_content.setGeometry(QtCore.QRect(0, 0, 811, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_license_scroll_content.sizePolicy().hasHeightForWidth())
        self.car_license_scroll_content.setSizePolicy(sizePolicy)
        self.car_license_scroll_content.setObjectName("car_license_scroll_content")
        self.car_fine_content = QtWidgets.QVBoxLayout(self.car_license_scroll_content)
        self.car_fine_content.setObjectName("car_fine_content")
        self.car_license_scroll.setWidget(self.car_license_scroll_content)
        self.tabLayout12.addWidget(self.car_license_scroll)
        self.tab.addTab(self.car_license_tab, "")
        self.mainpage_grid.addWidget(self.tab)
        self.logout_btn = QtWidgets.QPushButton(mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_btn.sizePolicy().hasHeightForWidth())
        self.logout_btn.setSizePolicy(sizePolicy)
        self.logout_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logout_btn.setObjectName("logout_btn")
        self.mainpage_grid.addWidget(self.logout_btn)

        self.retranslateUi(mainPage)
        self.tab.setCurrentIndex(0)
        self.passport_inner_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainPage)

    def retranslateUi(self, mainPage):
        _translate = QtCore.QCoreApplication.translate
        self.tab.setTabText(self.tab.indexOf(self.id_card_tab), _translate("mainPage", "Id card"))
        self.passport_inner_tab.setTabText(self.passport_inner_tab.indexOf(self.tab_visa), _translate("mainPage", "visa"))
        self.passport_inner_tab.setTabText(self.passport_inner_tab.indexOf(self.tab_borderstamp), _translate("mainPage", "borderstamp"))
        self.tab.setTabText(self.tab.indexOf(self.passport_tab), _translate("mainPage", "Passport"))
        self.tab.setTabText(self.tab.indexOf(self.car_license_tab), _translate("mainPage", "Car license"))
        self.add_car_btn.setText(_translate("mainPage", "+"))
        self.logout_btn.setText(_translate("mainPage", "Log out"))

class Border_guard_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Border_guard):
        Border_guard.setObjectName("Border_guard")
        Border_guard.resize(784, 476)
        self.border_grid = QtWidgets.QVBoxLayout(Border_guard)
        self.border_grid.setObjectName("border_grid")
        self.border_guard_groupBox = QtWidgets.QGroupBox(Border_guard)
        self.border_guard_groupBox.setObjectName("border_guard_groupBox")
        self.border_group_grid = QtWidgets.QVBoxLayout(self.border_guard_groupBox)
        self.border_group_grid.setObjectName("border_group_grid")
        self.border_guard_title = QtWidgets.QLabel(self.border_guard_groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.border_guard_title.setFont(font)
        self.border_guard_title.setToolTip("")
        self.border_guard_title.setStyleSheet("")
        self.border_guard_title.setAlignment(QtCore.Qt.AlignCenter)
        self.border_guard_title.setObjectName("border_guard_title")
        self.border_group_grid.addWidget(self.border_guard_title)
        self.border_guard_id_lay = QtWidgets.QHBoxLayout()
        self.border_guard_id_lay.setObjectName("border_guard_id_lay")
        self.border_guard_id_inp = QtWidgets.QLineEdit(self.border_guard_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_guard_id_inp.sizePolicy().hasHeightForWidth())
        self.border_guard_id_inp.setSizePolicy(sizePolicy)
        self.border_guard_id_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.border_guard_id_inp.setObjectName("border_guard_id_inp")
        self.border_guard_id_lay.addWidget(self.border_guard_id_inp)
        self.border_group_grid.addLayout(self.border_guard_id_lay)
        self.border_guard_loc_lay = QtWidgets.QHBoxLayout()
        self.border_guard_loc_lay.setObjectName("border_guard_loc_lay")
        self.border_guard_loc_inp = QtWidgets.QLineEdit(self.border_guard_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_guard_loc_inp.sizePolicy().hasHeightForWidth())
        self.border_guard_loc_inp.setSizePolicy(sizePolicy)
        self.border_guard_loc_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.border_guard_loc_inp.setObjectName("border_guard_loc_inp")
        self.border_guard_loc_lay.addWidget(self.border_guard_loc_inp)
        self.border_group_grid.addLayout(self.border_guard_loc_lay)
        self.border_guard_dir_lay = QtWidgets.QHBoxLayout()
        self.border_guard_dir_lay.setObjectName("border_guard_dir_lay")
        self.border_group_dir_com = QtWidgets.QComboBox(self.border_guard_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_group_dir_com.sizePolicy().hasHeightForWidth())
        self.border_group_dir_com.setSizePolicy(sizePolicy)
        self.border_group_dir_com.setMaximumSize(QtCore.QSize(200, 16777215))
        self.border_group_dir_com.setObjectName("border_group_dir_com")
        self.border_group_dir_com.addItem("")
        self.border_group_dir_com.addItem("")
        self.border_guard_dir_lay.addWidget(self.border_group_dir_com)
        self.border_group_grid.addLayout(self.border_guard_dir_lay)
        self.border_guard_submit_lay = QtWidgets.QHBoxLayout()
        self.border_guard_submit_lay.setObjectName("border_guard_submit_lay")
        self.border_guard_submit_btn = QtWidgets.QPushButton(self.border_guard_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_guard_submit_btn.sizePolicy().hasHeightForWidth())
        self.border_guard_submit_btn.setSizePolicy(sizePolicy)
        self.border_guard_submit_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.border_guard_submit_btn.setObjectName("border_guard_submit_btn")
        self.border_guard_submit_lay.addWidget(self.border_guard_submit_btn)
        self.border_group_grid.addLayout(self.border_guard_submit_lay)
        self.border_grid.addWidget(self.border_guard_groupBox)
        self.searchbar_title = QtWidgets.QLabel(Border_guard)
        self.searchbar_title.setObjectName("searchbar_title")
        self.border_grid.addWidget(self.searchbar_title)
        self.border_guard_box = QtWidgets.QHBoxLayout()
        self.border_guard_box.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.border_guard_box.setObjectName("border_guard_box")
        self.search_bar = QtWidgets.QLineEdit(Border_guard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_bar.sizePolicy().hasHeightForWidth())
        self.search_bar.setSizePolicy(sizePolicy)
        self.search_bar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_bar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_bar.setObjectName("search_bar")
        self.border_guard_box.addWidget(self.search_bar)
        self.border_guard_search_btn = QtWidgets.QPushButton(Border_guard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_guard_search_btn.sizePolicy().hasHeightForWidth())
        self.border_guard_search_btn.setSizePolicy(sizePolicy)
        self.border_guard_search_btn.setObjectName("border_guard_search_btn")
        self.border_guard_box.addWidget(self.border_guard_search_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.border_guard_box.addItem(spacerItem)
        self.border_guard_box.setStretch(0, 1)
        self.border_guard_box.setStretch(1, 4)
        self.border_grid.addLayout(self.border_guard_box)
        self.border_guard_scroll = QtWidgets.QScrollArea(Border_guard)
        self.border_guard_scroll.setWidgetResizable(True)
        self.border_guard_scroll.setObjectName("border_guard_scroll")
        self.border_guard_scroll_content = QtWidgets.QWidget()
        self.border_guard_scroll_content.setGeometry(QtCore.QRect(0, 0, 764, 56))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_guard_scroll_content.sizePolicy().hasHeightForWidth())
        self.border_guard_scroll_content.setSizePolicy(sizePolicy)
        self.border_guard_scroll_content.setObjectName("border_guard_scroll_content")
        self.scroll_grid = QtWidgets.QVBoxLayout(self.border_guard_scroll_content)
        self.scroll_grid.setObjectName("scroll_grid")
        
        self.border_guard_scroll.setWidget(self.border_guard_scroll_content)
        self.border_grid.addWidget(self.border_guard_scroll)
        self.border_guard_log_out_btn = QtWidgets.QPushButton(Border_guard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_guard_log_out_btn.sizePolicy().hasHeightForWidth())
        self.border_guard_log_out_btn.setSizePolicy(sizePolicy)
        self.border_guard_log_out_btn.setObjectName("border_guard_log_out_btn")
        self.border_grid.addWidget(self.border_guard_log_out_btn)

        self.retranslateUi(Border_guard)
        QtCore.QMetaObject.connectSlotsByName(Border_guard)

    def retranslateUi(self, Border_guard):
        _translate = QtCore.QCoreApplication.translate
        self.border_guard_title.setText(_translate("Border_guard", "Border stamp"))
        self.border_guard_id_inp.setPlaceholderText(_translate("Border_guard", "ID"))
        self.border_guard_loc_inp.setPlaceholderText(_translate("Border_guard", "Location"))
        self.border_group_dir_com.setItemText(0, _translate("Border_guard", "შესვლა"))
        self.border_group_dir_com.setItemText(1, _translate("Border_guard", "გასვლა"))
        self.border_guard_submit_btn.setText(_translate("Border_guard", "Submite"))
        self.searchbar_title.setText(_translate("Border_guard", "Search bar"))
        self.border_guard_search_btn.setText(_translate("Border_guard", "Search"))
        self.border_guard_log_out_btn.setText(_translate("Border_guard", "log out"))

class Police_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Police):
        Police.setObjectName("Police")
        Police.resize(919, 577)
        self.police_grid = QtWidgets.QVBoxLayout(Police)
        self.police_grid.setObjectName("police_grid")
        self.police_groupBox = QtWidgets.QGroupBox(Police)
        self.police_groupBox.setObjectName("police_groupBox")
        self.police_group_grid = QtWidgets.QVBoxLayout(self.police_groupBox)
        self.police_group_grid.setObjectName("police_group_grid")
        self.police_title = QtWidgets.QLabel(self.police_groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.police_title.setFont(font)
        self.police_title.setToolTip("")
        self.police_title.setStyleSheet("")
        self.police_title.setAlignment(QtCore.Qt.AlignCenter)
        self.police_title.setObjectName("police_title")
        self.police_group_grid.addWidget(self.police_title)
        self.police_id_lay = QtWidgets.QHBoxLayout()
        self.police_id_lay.setObjectName("police_id_lay")
        self.police_id_inp = QtWidgets.QLineEdit(self.police_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_id_inp.sizePolicy().hasHeightForWidth())
        self.police_id_inp.setSizePolicy(sizePolicy)
        self.police_id_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.police_id_inp.setObjectName("police_id_inp")
        self.police_id_lay.addWidget(self.police_id_inp)
        self.police_group_grid.addLayout(self.police_id_lay)
        self.police_type_lay = QtWidgets.QHBoxLayout()
        self.police_type_lay.setObjectName("police_type_lay")
        self.police_type_com = QtWidgets.QComboBox(self.police_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_type_com.sizePolicy().hasHeightForWidth())
        self.police_type_com.setSizePolicy(sizePolicy)
        self.police_type_com.setMaximumSize(QtCore.QSize(200, 16777215))
        self.police_type_com.setObjectName("police_type_com")
        self.police_type_com.addItem("")
        self.police_type_com.addItem("")
        self.police_type_com.addItem("")
        self.police_type_lay.addWidget(self.police_type_com)
        self.police_group_grid.addLayout(self.police_type_lay)
        self.police_car_lay = QtWidgets.QHBoxLayout()
        self.police_car_lay.setObjectName("police_car_lay")
        self.police_car_inp = QtWidgets.QLineEdit(self.police_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_car_inp.sizePolicy().hasHeightForWidth())
        self.police_car_inp.setSizePolicy(sizePolicy)
        self.police_car_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.police_car_inp.setObjectName("police_car_inp")
        self.police_car_lay.addWidget(self.police_car_inp)
        self.police_group_grid.addLayout(self.police_car_lay)
        self.police_msg_lay = QtWidgets.QHBoxLayout()
        self.police_msg_lay.setObjectName("police_msg_lay")
        self.police_msg_inp = QtWidgets.QLineEdit(self.police_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_msg_inp.sizePolicy().hasHeightForWidth())
        self.police_msg_inp.setSizePolicy(sizePolicy)
        self.police_msg_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.police_msg_inp.setObjectName("police_msg_inp")
        self.police_msg_lay.addWidget(self.police_msg_inp)
        self.police_group_grid.addLayout(self.police_msg_lay)
        self.police_amount_lay = QtWidgets.QHBoxLayout()
        self.police_amount_lay.setObjectName("police_amount_lay")
        self.police_amount_inp = QtWidgets.QLineEdit(self.police_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_amount_inp.sizePolicy().hasHeightForWidth())
        self.police_amount_inp.setSizePolicy(sizePolicy)
        self.police_amount_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.police_amount_inp.setObjectName("police_amount_inp")
        self.police_amount_lay.addWidget(self.police_amount_inp)
        self.police_group_grid.addLayout(self.police_amount_lay)
        self.police_dur_lay = QtWidgets.QHBoxLayout()
        self.police_dur_lay.setObjectName("police_dur_lay")
        self.police_dur_inp = QtWidgets.QLineEdit(self.police_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_dur_inp.sizePolicy().hasHeightForWidth())
        self.police_dur_inp.setSizePolicy(sizePolicy)
        self.police_dur_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.police_dur_inp.setObjectName("police_dur_inp")
        self.police_dur_lay.addWidget(self.police_dur_inp)
        self.police_group_grid.addLayout(self.police_dur_lay)
        self.police_submit_inp = QtWidgets.QHBoxLayout()
        self.police_submit_inp.setObjectName("police_submit_inp")
        self.police_submit_btn = QtWidgets.QPushButton(self.police_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_submit_btn.sizePolicy().hasHeightForWidth())
        self.police_submit_btn.setSizePolicy(sizePolicy)
        self.police_submit_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.police_submit_btn.setObjectName("police_submit_btn")
        self.police_submit_inp.addWidget(self.police_submit_btn)
        self.police_group_grid.addLayout(self.police_submit_inp)
        self.police_grid.addWidget(self.police_groupBox)
        self.police_search_bar_title = QtWidgets.QLabel(Police)
        self.police_search_bar_title.setObjectName("police_search_bar_title")
        self.police_grid.addWidget(self.police_search_bar_title)
        self.police_search_box = QtWidgets.QHBoxLayout()
        self.police_search_box.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.police_search_box.setObjectName("police_search_box")
        self.search_bar = QtWidgets.QLineEdit(Police)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_bar.sizePolicy().hasHeightForWidth())
        self.search_bar.setSizePolicy(sizePolicy)
        self.search_bar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_bar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_bar.setObjectName("search_bar")
        self.police_search_box.addWidget(self.search_bar)
        self.search_btn = QtWidgets.QPushButton(Police)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn.sizePolicy().hasHeightForWidth())
        self.search_btn.setSizePolicy(sizePolicy)
        self.search_btn.setObjectName("search_btn")
        self.police_search_box.addWidget(self.search_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.police_search_box.addItem(spacerItem)
        self.police_search_box.setStretch(0, 1)
        self.police_search_box.setStretch(1, 4)
        self.police_grid.addLayout(self.police_search_box)
        self.police_scroll = QtWidgets.QScrollArea(Police)
        self.police_scroll.setWidgetResizable(True)
        self.police_scroll.setObjectName("police_scroll")
        self.police_scroll_content = QtWidgets.QWidget()
        self.police_scroll_content.setGeometry(QtCore.QRect(0, 0, 899, 56))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_scroll_content.sizePolicy().hasHeightForWidth())
        self.police_scroll_content.setSizePolicy(sizePolicy)
        self.police_scroll_content.setObjectName("police_scroll_content")
        self.scroll_grid = QtWidgets.QVBoxLayout(self.police_scroll_content)
        self.scroll_grid.setObjectName("scroll_grid")
        
        self.police_scroll.setWidget(self.police_scroll_content)
        self.police_grid.addWidget(self.police_scroll)
        self.police_logout = QtWidgets.QPushButton(Police)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_logout.sizePolicy().hasHeightForWidth())
        self.police_logout.setSizePolicy(sizePolicy)
        self.police_logout.setObjectName("police_logout")
        self.police_grid.addWidget(self.police_logout)

        self.retranslateUi(Police)
        QtCore.QMetaObject.connectSlotsByName(Police)

    def retranslateUi(self, Police):
        _translate = QtCore.QCoreApplication.translate
        self.police_title.setText(_translate("Police", "Fine"))
        self.police_id_inp.setPlaceholderText(_translate("Police", "ID"))
        self.police_type_com.setItemText(0, _translate("Police", "ადმინისტრაციული"))
        self.police_type_com.setItemText(1, _translate("Police", "საგზაო"))
        self.police_type_com.setItemText(2, _translate("Police", "სხვა"))
        self.police_car_inp.setPlaceholderText(_translate("Police", "Car number"))
        self.police_msg_inp.setPlaceholderText(_translate("Police", "Message"))
        self.police_amount_inp.setPlaceholderText(_translate("Police", "Amount"))
        self.police_dur_inp.setPlaceholderText(_translate("Police", "Duration days"))
        self.police_submit_btn.setText(_translate("Police", "Submite"))
        self.police_search_bar_title.setText(_translate("Police", "Search bar"))
        self.search_btn.setText(_translate("Police", "Search"))
        self.police_logout.setText(_translate("Police", "log out"))


class Ambassador_page(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Ambassador):
        Ambassador.setObjectName("Ambassador")
        Ambassador.resize(919, 577)
        self.amb_grid = QtWidgets.QVBoxLayout(Ambassador)
        self.amb_grid.setObjectName("amb_grid")
        self.amb_groupBox = QtWidgets.QGroupBox(Ambassador)
        self.amb_groupBox.setObjectName("amb_groupBox")
        self.amb_group_grid = QtWidgets.QVBoxLayout(self.amb_groupBox)
        self.amb_group_grid.setObjectName("amb_group_grid")
        self.amb_title = QtWidgets.QLabel(self.amb_groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.amb_title.setFont(font)
        self.amb_title.setToolTip("")
        self.amb_title.setStyleSheet("")
        self.amb_title.setAlignment(QtCore.Qt.AlignCenter)
        self.amb_title.setObjectName("amb_title")
        self.amb_group_grid.addWidget(self.amb_title)
        self.amb_id_lay = QtWidgets.QHBoxLayout()
        self.amb_id_lay.setObjectName("amb_id_lay")
        self.amb_id_inp = QtWidgets.QLineEdit(self.amb_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amb_id_inp.sizePolicy().hasHeightForWidth())
        self.amb_id_inp.setSizePolicy(sizePolicy)
        self.amb_id_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.amb_id_inp.setObjectName("amb_id_inp")
        self.amb_id_lay.addWidget(self.amb_id_inp)
        self.amb_group_grid.addLayout(self.amb_id_lay)
        self.amb_type_lay = QtWidgets.QHBoxLayout()
        self.amb_type_lay.setObjectName("amb_type_lay")
        self.police_type_com = QtWidgets.QComboBox(self.amb_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.police_type_com.sizePolicy().hasHeightForWidth())
        self.police_type_com.setSizePolicy(sizePolicy)
        self.police_type_com.setMaximumSize(QtCore.QSize(200, 16777215))
        self.police_type_com.setObjectName("police_type_com")
        self.police_type_com.addItem("")
        self.police_type_com.addItem("")
        self.police_type_com.addItem("")
        self.police_type_com.addItem("")
        self.police_type_com.addItem("")
        self.police_type_com.addItem("")
        self.amb_type_lay.addWidget(self.police_type_com)
        self.amb_group_grid.addLayout(self.amb_type_lay)
        self.amb_country_lay = QtWidgets.QHBoxLayout()
        self.amb_country_lay.setObjectName("amb_country_lay")
        self.amb_country_inp = QtWidgets.QLineEdit(self.amb_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amb_country_inp.sizePolicy().hasHeightForWidth())
        self.amb_country_inp.setSizePolicy(sizePolicy)
        self.amb_country_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.amb_country_inp.setObjectName("amb_country_inp")
        self.amb_country_lay.addWidget(self.amb_country_inp)
        self.amb_group_grid.addLayout(self.amb_country_lay)
        self.amb_dur_lay = QtWidgets.QHBoxLayout()
        self.amb_dur_lay.setObjectName("amb_dur_lay")
        self.amb_dur_inp = QtWidgets.QLineEdit(self.amb_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amb_dur_inp.sizePolicy().hasHeightForWidth())
        self.amb_dur_inp.setSizePolicy(sizePolicy)
        self.amb_dur_inp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.amb_dur_inp.setObjectName("amb_dur_inp")
        self.amb_dur_lay.addWidget(self.amb_dur_inp)
        self.amb_group_grid.addLayout(self.amb_dur_lay)
        self.amb_submit_lay = QtWidgets.QHBoxLayout()
        self.amb_submit_lay.setObjectName("amb_submit_lay")
        self.amb_submit_btn = QtWidgets.QPushButton(self.amb_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amb_submit_btn.sizePolicy().hasHeightForWidth())
        self.amb_submit_btn.setSizePolicy(sizePolicy)
        self.amb_submit_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.amb_submit_btn.setObjectName("amb_submit_btn")
        self.amb_submit_lay.addWidget(self.amb_submit_btn)
        self.amb_group_grid.addLayout(self.amb_submit_lay)
        self.amb_grid.addWidget(self.amb_groupBox)
        self.amb_search_bar_title = QtWidgets.QLabel(Ambassador)
        self.amb_search_bar_title.setObjectName("amb_search_bar_title")
        self.amb_grid.addWidget(self.amb_search_bar_title)
        self.amb_search_box = QtWidgets.QHBoxLayout()
        self.amb_search_box.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.amb_search_box.setObjectName("amb_search_box")
        self.search_bar = QtWidgets.QLineEdit(Ambassador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_bar.sizePolicy().hasHeightForWidth())
        self.search_bar.setSizePolicy(sizePolicy)
        self.search_bar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_bar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_bar.setObjectName("search_bar")
        self.amb_search_box.addWidget(self.search_bar)
        self.amb_search_btn = QtWidgets.QPushButton(Ambassador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amb_search_btn.sizePolicy().hasHeightForWidth())
        self.amb_search_btn.setSizePolicy(sizePolicy)
        self.amb_search_btn.setObjectName("amb_search_btn")
        self.amb_search_box.addWidget(self.amb_search_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.amb_search_box.addItem(spacerItem)
        self.amb_search_box.setStretch(0, 1)
        self.amb_search_box.setStretch(1, 4)
        self.amb_grid.addLayout(self.amb_search_box)
        self.amb_scroll = QtWidgets.QScrollArea(Ambassador)
        self.amb_scroll.setWidgetResizable(True)
        self.amb_scroll.setObjectName("amb_scroll")
        self.amb_scroll_content = QtWidgets.QWidget()
        self.amb_scroll_content.setGeometry(QtCore.QRect(0, 0, 899, 56))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amb_scroll_content.sizePolicy().hasHeightForWidth())
        self.amb_scroll_content.setSizePolicy(sizePolicy)
        self.amb_scroll_content.setObjectName("amb_scroll_content")
        self.scroll_grid = QtWidgets.QVBoxLayout(self.amb_scroll_content)
        self.scroll_grid.setObjectName("scroll_grid")
        self.amb_scroll.setWidget(self.amb_scroll_content)
        self.amb_grid.addWidget(self.amb_scroll)
        self.amb_log_out_btn = QtWidgets.QPushButton(Ambassador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amb_log_out_btn.sizePolicy().hasHeightForWidth())
        self.amb_log_out_btn.setSizePolicy(sizePolicy)
        self.amb_log_out_btn.setObjectName("amb_log_out_btn")
        self.amb_grid.addWidget(self.amb_log_out_btn)

        self.retranslateUi(Ambassador)
        QtCore.QMetaObject.connectSlotsByName(Ambassador)

    def retranslateUi(self, Ambassador):
        _translate = QtCore.QCoreApplication.translate
        self.amb_title.setText(_translate("Ambassador", "Visa"))
        self.amb_id_inp.setPlaceholderText(_translate("Ambassador", "ID"))
        self.police_type_com.setItemText(0, _translate("Ambassador", "ტურისტული"))
        self.police_type_com.setItemText(1, _translate("Ambassador", "ბიზნეს"))
        self.police_type_com.setItemText(2, _translate("Ambassador", "საოჯახო"))
        self.police_type_com.setItemText(3, _translate("Ambassador", "სტუდენტური"))
        self.police_type_com.setItemText(4, _translate("Ambassador", "სამუშაო"))
        self.police_type_com.setItemText(5, _translate("Ambassador", "საცხოვრებელი"))
        self.amb_country_inp.setPlaceholderText(_translate("Ambassador", "Country"))
        self.amb_dur_inp.setPlaceholderText(_translate("Ambassador", "duration_years"))
        self.amb_submit_btn.setText(_translate("Ambassador", "Submite"))
        self.amb_search_bar_title.setText(_translate("Ambassador", "Search bar"))
        self.amb_search_btn.setText(_translate("Ambassador", "Search"))
        self.amb_log_out_btn.setText(_translate("Ambassador", "log out"))
