from PyQt5.QtWidgets import (QApplication, QSizePolicy, QMainWindow, QStackedWidget, QWidget, QPushButton, QVBoxLayout, 
                             QLabel, QLineEdit, QFormLayout, QHBoxLayout, QMessageBox, QDialog, QGridLayout)
from PyQt5 import QtCore, QtWidgets
import requests
from authentication import AppState
from database import Passport

class Home_window(QWidget):
    def __init__(self, My_window):
        super().__init__()
        self.setWindowTitle("Home")
        self.data = self.fetch()
        self.setupUi(self)

    def fetch(self):
        try:
            headers = {
                "Authorization": f"Bearer {AppState.token}"
            }

            user = requests.get("http://127.0.0.1:8000/data_fetch", headers=headers)
            fine = requests.get("http://127.0.0.1:8000/data_fetch/fine", headers=headers)
            borderstamp = requests.get("http://127.0.0.1:8000/data_fetch/borderstamp", headers=headers)
            visa = requests.get("http://127.0.0.1:8000/data_fetch/visa", headers=headers)
            
            if user.status_code == 200 and fine.status_code == 200 and borderstamp.status_code == 200 and visa.status_code == 200:
                return user.text, fine.json(), visa.text, borderstamp.text
            else:
                QMessageBox.warning(self, "Failed", f"Login failed:\n{user.json()}")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Error connecting to server:\n{str(e)}")

    # Generated UI code
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(992, 719)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.id_scroll = QtWidgets.QScrollArea(self.tab)
        self.id_scroll.setWidgetResizable(True)
        self.id_scroll.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.id_scroll.setObjectName("id_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 940, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout.addWidget(self.label_32)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout.addWidget(self.label_31)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.id_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.id_scroll)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.pass_scroll = QtWidgets.QScrollArea(self.tab_2)
        self.pass_scroll.setWidgetResizable(True)
        self.pass_scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pass_scroll.setObjectName("pass_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 940, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_11.setSpacing(7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_11.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_11.addWidget(self.label_40)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.pass_scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.pass_scroll)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_8.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 4, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.car_scroll = QtWidgets.QScrollArea(self.tab_3)
        self.car_scroll.setWidgetResizable(True)
        self.car_scroll.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.car_scroll.setObjectName("car_scroll")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 940, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_12.setSpacing(7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_12.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_12.addWidget(self.label_42)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_12.addWidget(self.pushButton_6)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.car_scroll.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.car_scroll)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", f"აიდი ნ: "))
        self.label_8.setText(_translate("Form", f"გაცემის თ: "))
        self.label_5.setText(_translate("Form", f"ვადის ამოწ "))
        self.label_7.setText(_translate("Form", "მოქ: georgia"))
        self.label_6.setText(_translate("Form", f"სქესი male"))
        self.label_4.setText(_translate("Form", f"პირადი ნ "))
        self.label_3.setText(_translate("Form", "გვარი"))
        self.label_2.setText(_translate("Form", "სახელი"))
        self.label.setText(_translate("Form", "დაბადებისთარიღი"))
        self.label_28.setText(_translate("Form", "****photo****"))
        self.label_32.setText(_translate("Form", "TextLabel"))
        self.label_31.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "ID card"))
        self.label_18.setText(_translate("Form", "პასპორტ ნ"))
        self.label_16.setText(_translate("Form", "გაცემის თ"))
        self.label_17.setText(_translate("Form", "ვადის ამოწ"))
        self.label_13.setText(_translate("Form", "გვარი"))
        self.label_10.setText(_translate("Form", "მოქ"))
        self.label_11.setText(_translate("Form", "სქესი"))
        self.label_12.setText(_translate("Form", "პირადი ნ"))
        self.label_14.setText(_translate("Form", "სახელი"))
        self.label_15.setText(_translate("Form", "დაბადებისთარიღი"))
        self.label_29.setText(_translate("Form", "****photo****"))
        self.label_39.setText(_translate("Form", "TextLabel"))
        self.label_40.setText(_translate("Form", "TextLabel"))
        self.pushButton_5.setText(_translate("Form", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Passport"))
        self.label_19.setText(_translate("Form", "გაცემის თ"))
        self.label_20.setText(_translate("Form", "ვადის ამოწ"))
        self.label_21.setText(_translate("Form", "მართვის მოწ ნომ"))
        self.label_27.setText(_translate("Form", "სახელი"))
        self.label_26.setText(_translate("Form", "დაბადებისთარიღი"))
        self.label_22.setText(_translate("Form", "მოქ"))
        self.label_23.setText(_translate("Form", "სქესი"))
        self.label_24.setText(_translate("Form", "პირადი ნ"))
        self.label_25.setText(_translate("Form", "გვარი"))
        self.label_30.setText(_translate("Form", "****photo****"))
        self.label_41.setText(_translate("Form", "TextLabel"))
        self.label_42.setText(_translate("Form", "TextLabel"))
        self.pushButton_6.setText(_translate("Form", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Car licese"))
        data = [
            {"date": "2024-01-12", "amount": "50 GEL", "reason": "Speeding"},
            {"date": "2024-02-10", "amount": "30 GEL", "reason": "Parking"},
            {"date": "2024-03-01", "amount": "70 GEL", "reason": "Red light"},
        ]
        self.populate_id_scroll(self.data[1])
    
    def populate_id_scroll(self, fines_data):
        for i in reversed(range(self.verticalLayout_8.count())):
            widget = self.verticalLayout_8.itemAt(i).widget()
            if widget is not None:
                widget.deleteLater()
        for fine in fines_data:
            layout = QtWidgets.QHBoxLayout()
            layout.setContentsMargins(5, 10, 5, 10)
            layout.setSpacing(7)
            date_label = QtWidgets.QLabel(f"Date: {fine['issue_date']}")
            amount_label = QtWidgets.QLabel(f"Amount: {fine['amount']}")
            push_button = QtWidgets.QPushButton("pushit")
            push_button.clicked.connect(lambda checked, b=push_button, id=fine["fine_id"]: self.test(b, id))

            layout.addWidget(date_label)
            layout.addWidget(amount_label)
            layout.addWidget(push_button)

            layout.setStretch(0, 1)
            layout.setStretch(1, 1)

            container = QtWidgets.QWidget()
            container.setLayout(layout)
            self.verticalLayout_8.addWidget(container)

    def test(self, but, id):
        but.setText("newtextt")
        print(id)
            